/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: SRQUnjGzm3+doL17tAkqETj74+XXcEsT6CmMvCuu7Yqy14mmR8JXCENug85Z4EZcjRo0MLGkDsJk5CIEhxDwFA==
 */

/* eslint-disable */
// tslint:disable

import Platform from './platform'

interface Conversation {
  createdAt: Date
  displayImageUrl: string
  displayName: string
  flag: number
  /**
   * @default nextval('conversation_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'conversation_id'}
  model: string
  /**
   * @default nextval('conversation_platform_seq'::regclass)
   */
  platform: Platform['id']
  systemMessage: string
  updatedAt: Date
}
export default Conversation;

interface Conversation_InsertParameters {
  createdAt: Date
  displayImageUrl: string
  displayName: string
  flag: number
  /**
   * @default nextval('conversation_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'conversation_id'}
  model: string
  /**
   * @default nextval('conversation_platform_seq'::regclass)
   */
  platform?: Platform['id']
  systemMessage: string
  updatedAt: Date
}
export type {Conversation_InsertParameters}
