/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 0gmI8fcL7dIF1dJA8R9HXKP54jEjrKqAQpbVBriaMA6cbxuaWj1kZfSHrzKH5FpLNYsKW+9E1aEVJdgo9WFJkw==
 */

/* eslint-disable */
// tslint:disable

interface Conversation {
  createdAt: string
  flag: number
  /**
   * @default nextval('conversation_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'conversation_id'}
  model: string
  systemMessage: string
  updatedAt: string
}
export default Conversation;

interface Conversation_InsertParameters {
  createdAt: string
  flag: number
  /**
   * @default nextval('conversation_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'conversation_id'}
  model: string
  systemMessage: string
  updatedAt: string
}
export type {Conversation_InsertParameters}
