/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: JUQBhGwyjeFmQQl9BTju0k10su4XKLVLj1boT91SEcXOCkfFTa+bl0BdxewTijfEvKuVIxgRbNaNY78SnfamGA==
 */

/* eslint-disable */
// tslint:disable

interface Conversation {
  createdAt: Date
  displayImageUrl: string
  displayName: string
  flag: number
  /**
   * @default nextval('conversation_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'conversation_id'}
  model: string
  systemMessage: string
  updatedAt: Date
  usedMessages: number
  usedTokens: number
}
export default Conversation;

interface Conversation_InsertParameters {
  createdAt: Date
  displayImageUrl: string
  displayName: string
  flag: number
  /**
   * @default nextval('conversation_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'conversation_id'}
  model: string
  systemMessage: string
  updatedAt: Date
  usedMessages: number
  usedTokens: number
}
export type {Conversation_InsertParameters}
