/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: wDgwZc8Oqf32pr552b0ZMkvXk1UP2XWk+VHK6kS6+gIt12jqvfMsLNu17l203JzIAmUW7BpV/af82l7DjysQXw==
 */

/* eslint-disable */
// tslint:disable

import Conversation from './conversation'
import User from './user'

interface ConversationMember {
  /**
   * @default nextval('"conversationMember_conversation_seq"'::regclass)
   */
  conversation: Conversation['id']
  createdAt: Date
  displayAvatarUrl: string
  displayBio: string
  displayName: string
  flag: number
  /**
   * @default nextval('"conversationMember_id_seq"'::regclass)
   */
  id: number & {readonly __brand?: 'conversationMember_id'}
  updatedAt: Date
  usedMessages: number
  usedTokens: number
  /**
   * @default nextval('"conversationMember_user_seq"'::regclass)
   */
  user: User['id']
}
export default ConversationMember;

interface ConversationMember_InsertParameters {
  /**
   * @default nextval('"conversationMember_conversation_seq"'::regclass)
   */
  conversation?: Conversation['id']
  createdAt: Date
  displayAvatarUrl: string
  displayBio: string
  displayName: string
  flag: number
  /**
   * @default nextval('"conversationMember_id_seq"'::regclass)
   */
  id?: number & {readonly __brand?: 'conversationMember_id'}
  updatedAt: Date
  usedMessages: number
  usedTokens: number
  /**
   * @default nextval('"conversationMember_user_seq"'::regclass)
   */
  user?: User['id']
}
export type {ConversationMember_InsertParameters}
