/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 3oR5NtmTNWG16Qoc3Qqkw6gFN3QZv/tT0wLZM/CAS9rSlybiqe3z/qodASilr4jrdjiWvyJqoVncRNagTCFB7Q==
 */

/* eslint-disable */
// tslint:disable

interface ConversationMember {
  createdAt: Date
  displayAvatarUrl: string
  displayBio: string
  displayName: string
  flag: number
  /**
   * @default nextval('"conversationMember_id_seq"'::regclass)
   */
  id: number & {readonly __brand?: 'conversationMember_id'}
  updatedAt: Date
  usedMessages: number
  usedTokens: number
}
export default ConversationMember;

interface ConversationMember_InsertParameters {
  createdAt: Date
  displayAvatarUrl: string
  displayBio: string
  displayName: string
  flag: number
  /**
   * @default nextval('"conversationMember_id_seq"'::regclass)
   */
  id?: number & {readonly __brand?: 'conversationMember_id'}
  updatedAt: Date
  usedMessages: number
  usedTokens: number
}
export type {ConversationMember_InsertParameters}
