/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: X/FCPY1ahErT9LLKs9dHw+48wPRBcwyoxkiV/Wz8Ao5zgdAyt17r69YdgirZTDJ8bLKCevVKSSuJ9ftW8Az79g==
 */

/* eslint-disable */
// tslint:disable

import AtdatabasesMigrationsApplied, {AtdatabasesMigrationsApplied_InsertParameters} from './atdatabases_migrations_applied'
import AtdatabasesMigrationsVersion, {AtdatabasesMigrationsVersion_InsertParameters} from './atdatabases_migrations_version'
import Conversation, {Conversation_InsertParameters} from './conversation'
import ConversationMember, {ConversationMember_InsertParameters} from './conversationMember'
import Message, {Message_InsertParameters} from './message'
import Platform, {Platform_InsertParameters} from './platform'
import User, {User_InsertParameters} from './user'

interface DatabaseSchema {
  atdatabases_migrations_applied: {record: AtdatabasesMigrationsApplied, insert: AtdatabasesMigrationsApplied_InsertParameters};
  atdatabases_migrations_version: {record: AtdatabasesMigrationsVersion, insert: AtdatabasesMigrationsVersion_InsertParameters};
  conversation: {record: Conversation, insert: Conversation_InsertParameters};
  conversationMember: {record: ConversationMember, insert: ConversationMember_InsertParameters};
  message: {record: Message, insert: Message_InsertParameters};
  platform: {record: Platform, insert: Platform_InsertParameters};
  user: {record: User, insert: User_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  AtdatabasesMigrationsApplied,
  AtdatabasesMigrationsApplied_InsertParameters,
  AtdatabasesMigrationsVersion,
  AtdatabasesMigrationsVersion_InsertParameters,
  Conversation,
  ConversationMember,
  ConversationMember_InsertParameters,
  Conversation_InsertParameters,
  Message,
  Message_InsertParameters,
  Platform,
  Platform_InsertParameters,
  User,
  User_InsertParameters,
}
