/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: aKR6BOzeJvWWkWsY2UIVZQsiilJ4xj509QzPcfBk+yh7iTcipSeSyoC32L+AioCTDfl1OsaJzoMWUc2/JazcwQ==
 */

/* eslint-disable */
// tslint:disable

import Conversation from './conversation'
import ConversationMember from './conversationMember'
import Platform from './platform'

interface Message {
  /**
   * @default nextval('message_author_seq'::regclass)
   */
  author: ConversationMember['id']
  content: string
  /**
   * @default nextval('message_conversation_seq'::regclass)
   */
  conversation: Conversation['id']
  createdAt: Date
  flag: number
  /**
   * @default nextval('message_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'message_id'}
  /**
   * @default nextval('message_platform_seq'::regclass)
   */
  platform: Platform['id']
  updatedAt: Date
}
export default Message;

interface Message_InsertParameters {
  /**
   * @default nextval('message_author_seq'::regclass)
   */
  author?: ConversationMember['id']
  content: string
  /**
   * @default nextval('message_conversation_seq'::regclass)
   */
  conversation?: Conversation['id']
  createdAt: Date
  flag: number
  /**
   * @default nextval('message_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'message_id'}
  /**
   * @default nextval('message_platform_seq'::regclass)
   */
  platform?: Platform['id']
  updatedAt: Date
}
export type {Message_InsertParameters}
