/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: zWUYUxQdx5P6WbQ0hgQlqBnAthdV7ESKGU+OH6iBJy8JN06jVGvXS+JGX8y3I1xuXMBZPVGHIPmRPFsU6p3Xwg==
 */

/* eslint-disable */
// tslint:disable

import Conversation from './conversation'
import ConversationMember from './conversationMember'

interface Message {
  /**
   * @default nextval('message_author_seq'::regclass)
   */
  author: ConversationMember['id']
  content: string
  /**
   * @default nextval('message_conversation_seq'::regclass)
   */
  conversation: Conversation['id']
  createdAt: Date
  flag: number
  /**
   * @default nextval('message_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'message_id'}
  updatedAt: Date
}
export default Message;

interface Message_InsertParameters {
  /**
   * @default nextval('message_author_seq'::regclass)
   */
  author?: ConversationMember['id']
  content: string
  /**
   * @default nextval('message_conversation_seq'::regclass)
   */
  conversation?: Conversation['id']
  createdAt: Date
  flag: number
  /**
   * @default nextval('message_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'message_id'}
  updatedAt: Date
}
export type {Message_InsertParameters}
