/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: PV56faRUo1+SvSfy0GaaL9KLxauejBVOPkDYEww2Xx+jx9pqszSmyD2dRNH2VbLD2VMmdLwOEweY4FRSn4VGaA==
 */

/* eslint-disable */
// tslint:disable

interface Platform {
  createdat: Date
  /**
   * @default nextval('platform_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'platform_id'}
  token: string
  updatedat: Date
  usedmessages: number
  usedtokens: number
}
export default Platform;

interface Platform_InsertParameters {
  createdat: Date
  /**
   * @default nextval('platform_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'platform_id'}
  token: string
  updatedat: Date
  usedmessages: number
  usedtokens: number
}
export type {Platform_InsertParameters}
