/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: RrIYrus33qEO9OX1kqf1tm/dasKTdKqBT3Bq7szpeG+eJyVlTilDCoKXVBa8uqyOd5adae1XbAdNBwE7pn5YOA==
 */

/* eslint-disable */
// tslint:disable

interface Platform {
  createdAt: Date
  displayImageUrl: string
  displayName: string
  flag: number
  /**
   * @default nextval('platform_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'platform_id'}
  token: string
  updatedAt: Date
  usedMessages: number
  usedTokens: number
}
export default Platform;

interface Platform_InsertParameters {
  createdAt: Date
  displayImageUrl: string
  displayName: string
  flag: number
  /**
   * @default nextval('platform_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'platform_id'}
  token: string
  updatedAt: Date
  usedMessages: number
  usedTokens: number
}
export type {Platform_InsertParameters}
