/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: YJv7aE1WfY9hPzGRVxPKmFuCRsbv6Oo0sSNr6ufoLgyJl87MFeejyn/P/GPGGSYGrL/MeivyoXpbNujd3LFiYw==
 */

/* eslint-disable */
// tslint:disable

import Platform from './platform'

interface PlatformUsage {
  flag: number
  /**
   * @default nextval('"platformUsage_id_seq"'::regclass)
   */
  id: number & {readonly __brand?: 'platformUsage_id'}
  model: string
  /**
   * @default nextval('"platformUsage_platform_seq"'::regclass)
   */
  platform: Platform['id']
  updatedAt: Date
  usedMessages: number
  usedTokens: number
}
export default PlatformUsage;

interface PlatformUsage_InsertParameters {
  flag: number
  /**
   * @default nextval('"platformUsage_id_seq"'::regclass)
   */
  id?: number & {readonly __brand?: 'platformUsage_id'}
  model: string
  /**
   * @default nextval('"platformUsage_platform_seq"'::regclass)
   */
  platform?: Platform['id']
  updatedAt: Date
  usedMessages: number
  usedTokens: number
}
export type {PlatformUsage_InsertParameters}
