/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: n8EeU83sLeCVUdB7Cn1jTLQ9Csv3SAA6Nl1DjMTw8VRfIkpp2utHO3UyuU5R8QljPEqj8LxNw1ptsGG4UVNVqQ==
 */

/* eslint-disable */
// tslint:disable

interface Platform {
  createdAt: Date
  flag: number
  /**
   * @default nextval('platform_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'platform_id'}
  name: string
  token: string
  updatedAt: Date
  usedMessages: number
  usedTokens: number
}
export default Platform;

interface Platform_InsertParameters {
  createdAt: Date
  flag: number
  /**
   * @default nextval('platform_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'platform_id'}
  name: string
  token: string
  updatedAt: Date
  usedMessages: number
  usedTokens: number
}
export type {Platform_InsertParameters}
