/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 49UF1S170cvbl6JBVqm1EWoTTHsVh8VAY9lRUkDtNim8WNFyTXPD7bk/uovesx3DxQAYqAfRQrU0NJ0aFIHHqg==
 */

/* eslint-disable */
// tslint:disable

interface User {
  createdat: Date
  displayavatarurl: string
  displaybio: string
  displayname: string
  flag: number
  /**
   * @default nextval('user_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'user_id'}
  password: string
  updatedat: Date
  usedmessages: number
  usedtokens: number
  username: string
}
export default User;

interface User_InsertParameters {
  createdat: Date
  displayavatarurl: string
  displaybio: string
  displayname: string
  flag: number
  /**
   * @default nextval('user_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'user_id'}
  password: string
  updatedat: Date
  usedmessages: number
  usedtokens: number
  username: string
}
export type {User_InsertParameters}
