/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: PBqhVYwFovsxCFLMK+KFeN/0l05r+wNIy07QirKYW0aVoU4CppkAEa/azLjO28Y+0/vp+0+tWP8QgakH7uTo7g==
 */

/* eslint-disable */
// tslint:disable

import Platform from './platform'

interface User {
  createdAt: Date
  displayAvatarUrl: string
  displayBio: string
  displayName: string
  flag: number
  /**
   * @default nextval('user_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'user_id'}
  password: string
  /**
   * @default nextval('user_platform_seq'::regclass)
   */
  platform: Platform['id']
  updatedAt: Date
  usedMessages: number
  usedTokens: number
  username: string
}
export default User;

interface User_InsertParameters {
  createdAt: Date
  displayAvatarUrl: string
  displayBio: string
  displayName: string
  flag: number
  /**
   * @default nextval('user_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'user_id'}
  password: string
  /**
   * @default nextval('user_platform_seq'::regclass)
   */
  platform?: Platform['id']
  updatedAt: Date
  usedMessages: number
  usedTokens: number
  username: string
}
export type {User_InsertParameters}
