/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 6OgFZaZGS9TTg/HMzCJdlFDaSBHcgm1Y+DkJbSl3SW7z8JkzPtbM+Aq/4eiitXBNveIAqqplJYxHYVWcfNYhSA==
 */

/* eslint-disable */
// tslint:disable

import User from './user'

interface UserUsage {
  flag: number
  /**
   * @default nextval('"userUsage_id_seq"'::regclass)
   */
  id: number & {readonly __brand?: 'userUsage_id'}
  model: string
  updatedAt: Date
  usedMessages: number
  usedTokens: number
  /**
   * @default nextval('"userUsage_user_seq"'::regclass)
   */
  user: User['id']
}
export default UserUsage;

interface UserUsage_InsertParameters {
  flag: number
  /**
   * @default nextval('"userUsage_id_seq"'::regclass)
   */
  id?: number & {readonly __brand?: 'userUsage_id'}
  model: string
  updatedAt: Date
  usedMessages: number
  usedTokens: number
  /**
   * @default nextval('"userUsage_user_seq"'::regclass)
   */
  user?: User['id']
}
export type {UserUsage_InsertParameters}
