/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 3ChUM27NPqchrmcKI741ZTnk1DDZceitZ38zaepV5M4yqLcFXzW4hRrGS1djC+5eoXhK7BgqskDpOCrHBGaYDg==
 */

/* eslint-disable */
// tslint:disable

import Platform from './platform'

interface User {
  createdAt: Date
  displayAvatarUrl: string
  displayBio: string
  displayName: string
  flag: number
  /**
   * @default nextval('user_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'user_id'}
  password: string
  /**
   * @default nextval('user_platform_seq'::regclass)
   */
  platform: Platform['id']
  updatedAt: Date
  username: string
}
export default User;

interface User_InsertParameters {
  createdAt: Date
  displayAvatarUrl: string
  displayBio: string
  displayName: string
  flag: number
  /**
   * @default nextval('user_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'user_id'}
  password: string
  /**
   * @default nextval('user_platform_seq'::regclass)
   */
  platform?: Platform['id']
  updatedAt: Date
  username: string
}
export type {User_InsertParameters}
