/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: zbgINiZoQ+P8xtk5OHOgJFJh+a406miyhbA78y9EGBSHfu3KbdYHOk5hcdGOCjoq1oJP7LMPvicwHY7lzOzg7Q==
 */

/* eslint-disable */
// tslint:disable

import Conversation from './conversation'
import Platform from './platform'
import User from './user'

interface ConversationMember {
  /**
   * @default nextval('"conversationMember_conversation_seq"'::regclass)
   */
  conversation: Conversation['id']
  createdAt: Date
  displayAvatarUrl: string
  displayBio: string
  displayName: string
  flag: number
  /**
   * @default nextval('"conversationMember_id_seq"'::regclass)
   */
  id: number & {readonly __brand?: 'conversationMember_id'}
  /**
   * @default nextval('"conversationMember_platform_seq"'::regclass)
   */
  platform: Platform['id']
  updatedAt: Date
  /**
   * @default nextval('"conversationMember_user_seq"'::regclass)
   */
  user: User['id']
}
export default ConversationMember;

interface ConversationMember_InsertParameters {
  /**
   * @default nextval('"conversationMember_conversation_seq"'::regclass)
   */
  conversation?: Conversation['id']
  createdAt: Date
  displayAvatarUrl: string
  displayBio: string
  displayName: string
  flag: number
  /**
   * @default nextval('"conversationMember_id_seq"'::regclass)
   */
  id?: number & {readonly __brand?: 'conversationMember_id'}
  /**
   * @default nextval('"conversationMember_platform_seq"'::regclass)
   */
  platform?: Platform['id']
  updatedAt: Date
  /**
   * @default nextval('"conversationMember_user_seq"'::regclass)
   */
  user?: User['id']
}
export type {ConversationMember_InsertParameters}
