/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: kx9IEoekkRdp1B1GFtKG7nMK8GP1J58il0XRbd9ByNdekUNnib4OPzg7jDYoINg7TjacPAmJ9BZ9ezLKGNa09Q==
 */

/* eslint-disable */
// tslint:disable

interface Platform {
  createdAt: Date
  displayImageUrl: string
  displayName: string
  flag: number
  /**
   * @default nextval('platform_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'platform_id'}
  inviteIdentifier: string
  token: string
  updatedAt: Date
}
export default Platform;

interface Platform_InsertParameters {
  createdAt: Date
  displayImageUrl: string
  displayName: string
  flag: number
  /**
   * @default nextval('platform_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'platform_id'}
  inviteIdentifier: string
  token: string
  updatedAt: Date
}
export type {Platform_InsertParameters}
